In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv("titanic_data_updated.csv")
df.sample(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
869,870,yes,third,"Johnson, Master. Harold Theodor",male,4.0,1,1,347742,11.1333,NaN,S
700,701,yes,first,"Astor, Mrs. John Jacob (Madeleine Talmadge Force)",female,18.0,1,0,PC 17757,227.5250,C62 C64,C

In [5]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [3]:
df.drop(['PassengerId','Name','Ticket','Cabin'],axis=1,inplace=True)

In [4]:
df.sample(3)

    Survived Pclass   Sex   Age  SibSp  Parch     Fare Embarked
453      yes  first  male  49.0      1      0  89.1042        C
643      yes  third  male   NaN      0      0  56.4958        S
575       no  third  male  19.0      0      0  14.5000        S

In [5]:
# x = feature columns
x = df.drop(['Survived'],axis=1)
# x.sample(3)

# y = traget column
y =  df['Survived']
y.sample(3)

123    yes
34      no
667     no
Name: Survived, dtype: object

Train-Test split - using scikit-learn

In [6]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [8]:
x_train.shape

(712, 7)

In [9]:
y_train.shape

(712,)

In [11]:
x_test.shape

(179, 7)

In [12]:
y_test.shape

(179,)