In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder, LabelEncoder, StandardScaler, MinMaxScaler
from sklearn.compose import ColumnTransformer

df = pd.read_csv("titanic_data_updated.csv")

In [12]:
df.sample(5)

    Survived  Pclass     Sex   Age  SibSp  Parch    Fare    Cabin Embarked
546      yes  second  female  19.0      1      0   26.00      NaN        S
297       no   first  female   2.0      1      2  151.55  C22 C26        S
323      yes  second  female  22.0      1      1   29.00      NaN        S
754      yes  second  female  48.0      1      2   65.00      NaN        S
612      yes   third  female   NaN      1      0   15.50      NaN        Q

Deleting useless columns

In [9]:
df.drop(['PassengerId','Name','Ticket'],axis=1,inplace=True)

Combining 'SibSp' and 'Parch' columns

In [ ]:
df['FamilyMembers'] = df['SibSp'] + df['Parch'] + 1 # 1 is for the person him/herself

In [15]:
df.drop(columns=['SibSp','Parch'],inplace=True)

In [17]:
df.sample(2)

    Survived  Pclass     Sex   Age    Fare Cabin Embarked  FamilyMembers
801      yes  second  female  31.0  26.250   NaN        S              3
414      yes   third    male  44.0   7.925   NaN        S              1

Train Test Split

In [18]:
x = df.drop(columns='Survived') # features
y = df['Survived'] # target

x_train, x_test, y_train, y_test = train_test_split(x,y,train_size=0.2, random_state=42)

Imputation