In [2]:
import pandas as pd

stdf = pd.read_csv('student_data.csv')
stdf.sample(3)

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi

In [3]:
import pandas as pd

data = {
    "Name": [
        "Jhon Doe", "David Ross", "Sarah Chen", "Mike Ross", "Emily White",
        "Liam O'Connor", "Sofia Rodriguez", "Aisha Khan", "Emily White",
        "Daniela Gomez", "Elena Petrova", "Jack Harrison"
    ],
    "City": [
        "North York", "New York", "Toronto", "Toronto", "London",
        "Dublin", "Madrid", "Dubai", "Tokyo",
        "Madrid", "Berlin", "Sydney"
    ],
    "Country": [
        "Canada", "US", "Canada", "Canada", "UK",
        "Ireland", "Spain", "UAE", "Ireland",
        'Spain', "Germany", "Australia"
    ],
    "Job Title": [
        "Software Engineer", "Backend Developer", "Data Scientist", "Project Manager", "UX Designer",
        "DevOps Engineer", "Frontend Developer", "Product Manager", "Systems Architect",
        "Data Analyst", "Security Engineer", "QA Engineer"
    ],
    "Salary": [
        160000, 155000, 145000, 130000, 120000,
        140000, 115000, 170000, 180000,
        95000, 135000, 110000
    ]
}

df = pd.DataFrame(data)

               Name        City    Country           Job Title  Salary
0          Jhon Doe  North York     Canada   Software Engineer  160000
1        David Ross    New York         US   Backend Developer  155000
2        Sarah Chen     Toronto     Canada      Data Scientist  145000
3         Mike Ross     Toronto     Canada     Project Manager  130000
4       Emily White      London         UK         UX Designer  120000
5     Liam O'Connor      Dublin    Ireland     DevOps Engineer  140000
6   Sofia Rodriguez      Madrid      Spain  Frontend Developer  115000
7        Aisha Khan       Dubai        UAE     Product Manager  170000
8       Emily White       Tokyo    Ireland   Systems Architect  180000
9     Daniela Gomez      Madrid      Spain        Data Analyst   95000
10    Elena Petrova      Berlin    Germany   Security Engineer  135000
11    Jack Harrison      Sydney  Australia         QA Engineer  110000

In [4]:
df['Salary'].sum()

np.int64(1655000)

In [5]:
df['Salary'].mean()

np.float64(137916.66666666666)

In [9]:
df['Salary'].median()

np.float64(137500.0)

In [19]:
df['Salary'].min()

np.int64(95000)

In [20]:
df['Salary'].max()

np.int64(180000)

Standard Deviation

In [17]:
df['Salary'].std()

np.float64(25535.92241007427)

Summation of "Data Structure, Python and Algorithm Marks" - using column index

In [13]:
stdf['Total Marks'] = stdf.iloc[:,2:5].sum(axis=1)
stdf.sample(3)

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Total Marks
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram,188.0
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,228.0
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi,0.0

summation of different columns - row-wise

In [15]:
stdf[['Data Structure Marks','Python Marks']].sum()
# total Data Structure Marks of all students combined
# total Python Marks of all students combined

Data Structure Marks    1344.0
Python Marks            1285.0
dtype: float64

correlation between two columns values

In [18]:
stdf[['Data Structure Marks','Python Marks']].corr()

                      Data Structure Marks  Python Marks
Data Structure Marks              1.000000      0.893455
Python Marks                      0.893455      1.000000

Standard Deviation

In [16]:
stdf['Python Marks'].std()

np.float64(5.394000194219323)