Encoding:
- Ordinary - There is an order in data, {First class, Second class, Third Class}, {MSc,BSc, HSC} etc.
- Nominal - no order in data, Gender, Color, Type etc.

In [ ]:
import pandas as pd

# index_col = 0 --> restored original index
x_train = pd.read_csv("titanic_x_train.csv",index_col = 0)
x_test = pd.read_csv("titanic_x_test.csv",index_col = 0)
x_train.drop(['z_score_age','z_score_fare'],axis=1,inplace=True)

In [46]:
x_train.head(4)

,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked,Cabin_Missing_Indicator
331,first,male,45.5,0,0,28.5000,C124,S,False
733,second,male,23.0,0,0,13.0000,Missing,S,True
382,third,male,32.0,0,0,7.9250,Missing,S,True
704,third,male,26.0,1,0,7.8542,Missing,S,True

In [47]:
x_test.sample(3)

,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked,Cabin_Missing_Indicator
280,third,male,65.000000,0,0,7.7500,Missing,Q,True
375,first,female,29.498846,1,0,82.1708,Missing,C,True
739,third,male,29.498846,0,0,7.8958,Missing,S,True

Ordinal Encoder - encode categorical features as an integer array

In [48]:
from sklearn.preprocessing import OrdinalEncoder
pclass_encoder = OrdinalEncoder(categories=[['third','second','first']]) # in ascending order 

# fit --for training data only
pclass_encoder.fit(x_train[['Pclass']])

# transform -- for both training data and test data
x_train['Pclass_encoded'] = pclass_encoder.transform(x_train[['Pclass']]).ravel()
x_test['Pclass_encoded'] = pclass_encoder.transform(x_test[['Pclass']]).ravel()

Deleting 'Pclass' column as it has been encoded

In [49]:
x_train.drop('Pclass',axis=1,inplace=True)

In [51]:
x_train.head(5)

,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked,Cabin_Missing_Indicator,Pclass_encoded
331,male,45.5,0,0,28.5000,C124,S,False,2.0
733,male,23.0,0,0,13.0000,Missing,S,True,1.0
382,male,32.0,0,0,7.9250,Missing,S,True,0.0
704,male,26.0,1,0,7.8542,Missing,S,True,0.0
813,female,6.0,4,2,31.2750,Missing,S,True,0.0

In [52]:
x_test.drop('Pclass',axis=1,inplace=True)

In [53]:
x_test.head(3)

,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked,Cabin_Missing_Indicator,Pclass_encoded
709,male,29.498846,1,1,15.2458,Missing,C,True,0.0
439,male,31.000000,0,0,10.5000,Missing,S,True,1.0
840,male,20.000000,0,0,7.9250,Missing,S,True,0.0

One hot encoder - encoding Nominal Data. <br>
Encode categorical features as a one-hot numeric array.

OneHotEncoding for 'Sex' column

In [54]:
from sklearn.preprocessing import OneHotEncoder

sex_ohe = OneHotEncoder(sparse_output=False).set_output(transform='pandas')

# fit
sex_ohe.fit(x_train[['Sex']])

# transform
encoded_sex_df_train = sex_ohe.transform(x_train[['Sex']])
encoded_sex_df_test = sex_ohe.transform(x_test[['Sex']])

# concatenating encoded_sex_df with x_train and x_test df
x_train = pd.concat([x_train,encoded_sex_df_train],axis=1)
x_test = pd.concat([x_test,encoded_sex_df_test],axis=1)

In [55]:
x_train.sample(2)

,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked,Cabin_Missing_Indicator,Pclass_encoded,Sex_female,Sex_male
185,male,29.498846,0,0,50.0,A32,S,False,2.0,0.0,1.0
178,male,30.000000,0,0,13.0,Missing,S,True,1.0,0.0,1.0

In [56]:
# dropping 'Sex' column as it is now encoded
x_train.drop(columns='Sex',inplace=True)
x_test.drop('Sex',axis=1,inplace=True)

# both ways of deleting columns are correct

In [12]:
# x_test.sample(2)

OneHotEncoding for 'Embarked' column

In [57]:
embarked_ohe = OneHotEncoder(sparse_output=False).set_output(transform='pandas')

# fit
embarked_ohe.fit(x_train[['Embarked']])

# transform
encoded_embarked_df_train = embarked_ohe.transform(x_train[['Embarked']])
encoded_embarked_df_test = embarked_ohe.transform(x_test[['Embarked']])

# concatenating df's
x_train = pd.concat([x_train,encoded_embarked_df_train],axis=1)
x_test = pd.concat([x_test,encoded_embarked_df_test],axis=1)

In [58]:
# dropping "Embarked" column as it is now encoded
x_train.drop(columns='Embarked',inplace=True)
x_test.drop(columns='Embarked',inplace=True)

In [ ]:
# x_train.sample(3)
# x_test.sample(3)

### Encoding the 'Cabin' column

In [ ]:
# making a column with the first Character of Cabin name which is 'deck' 
x_train['Cabin_deck'] = x_train['Cabin'].astype(str).str[0];
x_test['Cabin_deck'] = x_test['Cabin'].astype(str).str[0];

In [ ]:
# x_train.sample(5)
# x_test.sample(5)

Now, one hot encoding for 'Cabin_deck' column

In [62]:
deck_ohe = OneHotEncoder(sparse_output=False).set_output(transform='pandas')

# fit
deck_ohe.fit(x_train[['Cabin_deck']])

# transform
encoded_deck_df_train = deck_ohe.transform(x_train[['Cabin_deck']])
encoded_deck_df_test = deck_ohe.transform(x_test[['Cabin_deck']])

# concate df
x_train = pd.concat([x_train, encoded_deck_df_train],axis=1)
x_test = pd.concat([x_test, encoded_deck_df_test],axis=1)

In [63]:
x_test.head(10)

,Age,SibSp,Parch,Fare,Cabin,Cabin_Missing_Indicator,Pclass_encoded,Sex_female,Sex_male,Embarked_C,...,Cabin_deck,Cabin_deck_A,Cabin_deck_B,Cabin_deck_C,Cabin_deck_D,Cabin_deck_E,Cabin_deck_F,Cabin_deck_G,Cabin_deck_M,Cabin_deck_T
709,29.498846,1,1,15.2458,Missing,True,0.0,0.0,1.0,1.0,...,M,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
439,31.000000,0,0,10.5000,Missing,True,1.0,0.0,1.0,0.0,...,M,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
840,20.000000,0,0,7.9250,Missing,True,0.0,0.0,1.0,0.0,...,M,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
720,6.000000,0,1,33.0000,Missing,True,1.0,1.0,0.0,0.0,...,M,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
39,14.000000,1,0,11.2417,Missing,True,0.0,1.0,0.0,1.0,...,M,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
290,26.000000,0,0,78.8500,Missing,True,2.0,1.0,0.0,0.0,...,M,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
300,29.498846,0,0,7.7500,Missing,True,0.0,1.0,0.0,0.0,...,M,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
333,16.000000,2,0,18.0000,Missing,True,0.0,0.0,1.0,0.0,...,M,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
208,16.000000,0,0,7.7500,Missing,True,0.0,1.0,0.0,0.0,...,M,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
136,19.000000,0,2,26.2833,D47,False,2.0,1.0,0.0,0.0,...,D,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [64]:
x_train.drop(columns='Cabin_deck',axis=1,inplace=True)
x_test.drop(columns='Cabin_deck',axis=1,inplace=True)

In [65]:
x_train.head(5)

,Age,SibSp,Parch,Fare,Cabin,Cabin_Missing_Indicator,Pclass_encoded,Sex_female,Sex_male,Embarked_C,...,Embarked_S,Cabin_deck_A,Cabin_deck_B,Cabin_deck_C,Cabin_deck_D,Cabin_deck_E,Cabin_deck_F,Cabin_deck_G,Cabin_deck_M,Cabin_deck_T
331,45.5,0,0,28.5000,C124,False,2.0,0.0,1.0,0.0,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
733,23.0,0,0,13.0000,Missing,True,1.0,0.0,1.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
382,32.0,0,0,7.9250,Missing,True,0.0,0.0,1.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
704,26.0,1,0,7.8542,Missing,True,0.0,0.0,1.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
813,6.0,4,2,31.2750,Missing,True,0.0,1.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

### **Label Encoder** - encoding 'Target' column (y_train, y_test)

In [66]:
y_train = pd.read_csv("titanic_y_train.csv",index_col=0).squeeze('columns')
y_test = pd.read_csv("titanic_y_test.csv",index_col=0).squeeze('columns')
y_train.head(5)

331    no
733    no
382    no
704    no
813    no
Name: Survived, dtype: object

In [67]:
from sklearn.preprocessing import LabelEncoder

lable_encoder = LabelEncoder()

# fit
lable_encoder.fit(y_train) # no need to pass column name, as it's just a series already(one column only)

# transform
y_train_array = lable_encoder.transform(y_train)
y_test_array = lable_encoder.transform(y_test)

In [68]:
y_train_array

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 0])

In [69]:
print(type(y_train))
print(type(y_test))

<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>

Converting y_train and y_test array to pandas series

In [70]:
y_train = pd.Series(y_train_array,index=y_train.index,name=y_train.name)
y_test = pd.Series(y_test_array,index=y_test.index,name=y_test.name)

In [73]:
display(y_train.head(5))
print("------------------------")
display(y_test.head(5))

331    0
733    0
382    0
704    0
813    0
Name: Survived, dtype: int64

------------------------

709    1
439    0
840    0
720    1
39     1
Name: Survived, dtype: int64