Encoding:
- Ordinary - There is an order in data, {First class, Second class, Third Class}, {MSc,BSc, HSC} etc.
- Nominal - no order in data, Gender, Color, Type etc.

In [1]:
import pandas as pd

x_train = pd.read_csv("titanic_x_train.csv")
x_test = pd.read_csv("titanic_x_test.csv")
x_train.drop(['z_score_age','z_score_fare'],axis=1,inplace=True)

In [2]:
x_train.sample(4)

,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked,Cabin_Missing_Indicator
18,second,male,34.000000,0,0,13.0000,Missing,S,True
342,third,female,29.498846,8,2,64.3625,Missing,S,True
71,third,female,30.000000,0,0,12.4750,Missing,S,True
573,third,female,29.498846,0,0,7.7500,Missing,Q,True

In [3]:
x_test.sample(3)

,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked,Cabin_Missing_Indicator
60,third,male,21.0,0,0,7.7750,Missing,S,True
152,third,male,18.0,0,0,7.7958,Missing,S,True
74,third,male,23.0,0,0,7.8542,Missing,S,True

Ordinal Encoder - encode categorical features as an integer array

In [4]:
from sklearn.preprocessing import OrdinalEncoder
pclass_encoder = OrdinalEncoder(categories=[['third','second','first']]) # in ascending order 

# fit --for training data only
pclass_encoder.fit(x_train[['Pclass']])

# transform -- for both training data and test data
x_train['Pclass_encoded'] = pclass_encoder.transform(x_train[['Pclass']]).ravel()
x_test['Pclass_encoded'] = pclass_encoder.transform(x_test[['Pclass']]).ravel()

Deleting 'Pclass' column as it has been encoded

In [8]:
x_train.drop('Pclass',axis=1,inplace=True)

In [9]:
x_train.sample(5)

,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked,Cabin_Missing_Indicator,Pclass_encoded
322,female,30.000000,1,1,24.1500,Missing,S,True,0.0
318,female,28.000000,0,0,7.8958,Missing,S,True,0.0
672,male,62.000000,0,0,26.5500,C87,S,False,2.0
527,male,0.420000,0,1,8.5167,Missing,C,True,0.0
281,male,29.498846,0,0,7.7500,Missing,Q,True,0.0

In [10]:
x_test.drop('Pclass',axis=1,inplace=True)

In [11]:
x_test.sample(3)

,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked,Cabin_Missing_Indicator,Pclass_encoded
22,female,19.000000,1,0,7.8542,Missing,S,True,0.0
110,female,29.498846,1,0,52.0000,C126,S,False,2.0
64,male,29.498846,0,0,7.7500,Missing,Q,True,0.0

One hot encoder - encoding Nominal Data. <br>
Encode categorical features as a one-hot numeric array.

OneHotEncoding for 'Sex' column

In [12]:
from sklearn.preprocessing import OneHotEncoder

sex_ohe = OneHotEncoder(sparse_output=False).set_output(transform='pandas')

# fit
sex_ohe.fit(x_train[['Sex']])

# transform
encoded_sex_df_train = sex_ohe.transform(x_train[['Sex']])
encoded_sex_df_test = sex_ohe.transform(x_test[['Sex']])

# concatenating encoded_sex_df with x_train and x_test df
x_train = pd.concat([x_train,encoded_sex_df_train],axis=1)
x_test = pd.concat([x_test,encoded_sex_df_test],axis=1)

In [14]:
x_train.sample(2)

,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked,Cabin_Missing_Indicator,Pclass_encoded,Sex_female,Sex_male
383,female,48.0,0,0,25.9292,D17,S,False,2.0,1.0,0.0
163,male,9.0,4,2,31.3875,Missing,S,True,0.0,0.0,1.0

In [15]:
# dropping 'Sex' column as it is now encoded
x_train.drop(columns='Sex',inplace=True)
x_test.drop('Sex',axis=1,inplace=True)

# both ways of deleting columns are correct

In [ ]:
# x_test.sample(2)

,Age,SibSp,Parch,Fare,Cabin,Embarked,Cabin_Missing_Indicator,Pclass_encoded,Sex_female,Sex_male
34,18.0,0,0,8.05,Missing,S,True,0.0,0.0,1.0
54,65.0,0,0,7.75,Missing,Q,True,0.0,0.0,1.0

OneHotEncoding for 'Embarked' column

In [18]:
embarked_ohe = OneHotEncoder(sparse_output=False).set_output(transform='pandas')

# fit
embarked_ohe.fit(x_train[['Embarked']])

# transform
encoded_embarked_df_train = embarked_ohe.transform(x_train[['Embarked']])
encoded_embarked_df_test = embarked_ohe.transform(x_test[['Embarked']])

# concatenating df's
x_train = pd.concat([x_train,encoded_embarked_df_train],axis=1)
x_test = pd.concat([x_test,encoded_embarked_df_test],axis=1)

In [ ]:
# dropping "Embarked" column as it is now encoded
x_train.drop(columns='Embarked',inplace=True)
x_test.drop(columns='Embarked',inplace=True)

In [ ]:
# x_train.sample(3)
# x_test.sample(3)

,Age,SibSp,Parch,Fare,Cabin,Cabin_Missing_Indicator,Pclass_encoded,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S
124,25.00,0,0,7.250,Missing,True,0.0,0.0,1.0,0.0,0.0,1.0
123,0.83,0,2,29.000,Missing,True,1.0,0.0,1.0,0.0,0.0,1.0
67,29.00,0,0,7.875,Missing,True,0.0,0.0,1.0,0.0,0.0,1.0