Encoding:
- Ordinary - There is an order in data, {First class, Second class, Third Class}, {MSc,BSc, HSC} etc.
- Nominal - no order in data, Gender, Color, Type etc.

In [1]:
import pandas as pd

x_train = pd.read_csv("titanic_x_train.csv")
x_test = pd.read_csv("titanic_x_test.csv")
x_train.drop(['z_score_age','z_score_fare'],axis=1,inplace=True)

In [2]:
x_train.sample(4)

,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked,Cabin_Missing_Indicator
18,second,male,34.000000,0,0,13.0000,Missing,S,True
342,third,female,29.498846,8,2,64.3625,Missing,S,True
71,third,female,30.000000,0,0,12.4750,Missing,S,True
573,third,female,29.498846,0,0,7.7500,Missing,Q,True

In [3]:
x_test.sample(3)

,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked,Cabin_Missing_Indicator
60,third,male,21.0,0,0,7.7750,Missing,S,True
152,third,male,18.0,0,0,7.7958,Missing,S,True
74,third,male,23.0,0,0,7.8542,Missing,S,True

Ordinal Encoder - encode categorical features as an integer array

In [4]:
from sklearn.preprocessing import OrdinalEncoder
pclass_encoder = OrdinalEncoder(categories=[['third','second','first']]) # in ascending order 

# fit --for training data only
pclass_encoder.fit(x_train[['Pclass']])

# transform -- for both training data and test data
x_train['Pclass_encoded'] = pclass_encoder.transform(x_train[['Pclass']]).ravel()
x_test['Pclass_encoded'] = pclass_encoder.transform(x_test[['Pclass']]).ravel()

In [5]:
x_train.sample(5)

,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked,Cabin_Missing_Indicator,Pclass_encoded
701,third,female,16.000000,5,2,46.9000,Missing,S,True,0.0
10,second,female,42.000000,0,0,13.0000,Missing,S,True,1.0
495,first,female,54.000000,1,0,64.3625,D20,C,False,2.0
238,second,male,27.000000,0,0,13.0000,Missing,S,True,1.0
519,third,male,29.498846,8,2,64.3625,Missing,S,True,0.0

In [7]:
x_test.sample(3)

,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked,Cabin_Missing_Indicator,Pclass_encoded
120,second,male,23.000000,2,1,11.5000,Missing,S,True,1.0
92,first,male,61.000000,0,0,32.3208,D50,S,False,2.0
24,third,male,29.498846,0,0,14.5000,Missing,S,True,0.0